### ISSUE TITLE
kaitai is failing to install

### ISSUE THREAD

**Issue by nov3mb3r** [KOLANICH-tools/WindowsTelemetryViewer.py#1]
Following the instructions of readme some dependencies are needed. kaitai.compass cannot be installed via pip
```
sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    formatsPath = thisDir / "kaitai_struct_formats"
NameError: name 'thisDir' is not defined
```

**Comment by KOLANICH** [comment]
I'm sorry for the late response, just saw this issue. We don't use `setup.py` anymore. We use declarative configuration in `pyproject.toml` for quite some time. Should work since then.
